### builder stage ###
FROM alpine:3.20.3 AS builder

RUN apk add --no-cache openjdk17-jdk

COPY ./target/*.jar /app/app.jar

RUN mkdir /app/unpacked && \
    unzip /app/app.jar -d /app/unpacked && \
    jdeps \
    --ignore-missing-deps \
    -q \
    --recursive \
    --multi-release 17 \
    --print-module-deps \
    --class-path="/app/unpacked/BOOT-INF/lib/*" \
    /app/app.jar > /app/dependencies.info && \
    rm -rf /app/unpacked

RUN jlink --verbose \
    --compress 2 \
    --strip-java-debug-attributes \
    --no-header-files \
    --no-man-pages \
    --output /jre \
    --add-modules $(cat /app/dependencies.info)

RUN cd /app && \
    java -Djarmode=layertools -jar app.jar extract

### app stage ###
FROM alpine:3.20.3

ENV JAVA_HOME=/jre
ENV PATH="${JAVA_HOME}/bin:${PATH}"

COPY ./target/*.jar /app/app.jar

RUN addgroup -g 1000 -S hello && \
    adduser -u 1000 -G hello -D hello && \
    chown -R hello /app

COPY --from=builder /jre $JAVA_HOME

USER hello

WORKDIR /app

EXPOSE 8080

CMD java -Djava.security.egd=file:/dev/./urandom -jar /app/app.jar
